---
name: Playwright

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Doppler
        run: wget -t 3 -qO- https://cli.doppler.com/install.sh | sudo sh

      # Docker isn't included in the macOS images
      - uses: better0fdead/actions-setup-docker@better0fdead/increase-timeout
        timeout-minutes: 20

      - name: Start Docker Compose
        run: doppler run --mount .env -- docker compose up -d
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: doppler run -- npm run test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: always()
        with:
          name: test-results
          path: test-results/

  test-ct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - run: npm run test-ct

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
